name: isl
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  google_ml_kit: ^0.11.0
  speech_to_text: ^6.0.0
  flutter_tts: ^3.5.0
  path_provider: ^2.0.11
  provider: ^6.1.2
  tflite_flutter: ^0.9.4
  tflite_flutter_helper: ^0.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^2.10.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.10.0
  url_launcher: ^6.0.20
  youtube_player_flutter: ^8.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    -  assets/image/sanchaar.png
    -  assets/image/app_logo.jpg
    -  assets/image/isl_alphabet.jpg
    -  assets/image/isl_number.jpg
